#!/usr/bin/env bash

declare part="${1:-1}"
declare data="${2:-test}"
declare day="${3:-$(printf "%d" $(date +%d))}"

declare invocation="echo Part $part \($data\) on Day $day; cd day-${day} && ./solution.jq $part-$data.dat"

ls * | entr -c bash -c "$invocation"
