#!/usr/bin/env bash

declare day="${1:?Specify Day}"
declare part="${2:-1}"
declare data="${3:-test}"

declare invocation="echo Day $day Part $part \($data\); cd day-${day} && ./solution.jq $part-$data.dat"

find day-${day}* | entr -c bash -c "$invocation"
