#!/usr/bin/env bash

set -eo pipefail

declare day="${1:?Specify day to run}"

# Use test data unless env var PRODUCTION is set
[[ $PRD -eq 1 ]] && data=input.dat || data=test.dat

jq -L . -f "$day/solution.jq" -R -s "$day/$data"
